wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1685629823.427219
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
batch_size_loop:
  desc: null
  value: 64
batch_size_paired:
  desc: null
  value: 128
dataset:
  desc: null
  value: MNIST-FMNIST
epochs:
  desc: null
  value: 3000
image_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.001
loss_function:
  desc: null
  value: l1_loss
machine:
  desc: null
  value: Colab
model:
  desc: null
  value: dense_icnn
